name: Fetch Matches Cron

# Runs every 30 minutes
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:  # allows manual trigger

jobs:
  fetch-matches:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run your script
      - name: Run fetch script
        run: node yourScript.js
